photosite/config/routes.rb
 Rails.application.routes.draw do
  get '/cloud/show/:id', to: 'cloud#show', as: "cloud_show"
  get '/uploads/new/:id', to: 'uploads#new', as: "uploads_new"
  get '/slide_show/show/:id', to: 'slide_show#show', as: "slideshow_show"
  get '/slide_show/create/:id', to: 'slide_show#create', as: "slideshow_create"
  resources :user do
  	resources :uploads
    resources :slide_shows
  end
  devise_scope :user do
	  get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users
  root 'page#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

photosite/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

photosite/app/models/slide_show.rb
class SlideShow < ApplicationRecord
  belongs_to :user
    has_attached_file :image, :styles => { :medium => "300x300>",:thumb => "100x100>" }
	
	validates_attachment 	:image, 
							:presence => true,
							:content_type => { :content_type => /\Aimage\/.*\Z/ }
end

photosite/app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>",:thumb => "100x100>" }
	
	validates_attachment 	:image, 
				:presence => true,
	:content_type => { :content_type => /\Aimage\/.*\Z/ }
end

photosite/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :uploads
  has_many :slide_shows
end

photosite/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
	user_path(current_user)
  end
end

photosite/app/controllers/cloud_controller.rb
class CloudController < ApplicationController
  def index

  end

  def show
    @user = User.find(params[:id])
  end
end

photosite/app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

photosite/app/controllers/slide_show_controller.rb
class SlideShowController < ApplicationController
  def index
  	
  end

  def new 
    @user = User.find(params[:id])
  	@slide_show = SlideShow.new
  end 

  def create
  	@user = User.find(params[:id])
  	@slide_show = @user.slide_shows.create()
  	if @slide_show.save
  		@user.slide_shows.push(@slide_show)
  end
    end

  def show
    @user = User.find(params[:id])
  end

end

photosite/app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def new
    @user = User.find(params[:id])
    @upload = Upload.new
  end

  def edit
    @user = User.find(params[:user_id])
    @upload = Upload.find(params[:id])
  end

  def create
    @user = User.find(params[:user_id])
	  @upload = @user.uploads.create(upload_params)
  	if @upload.save
  	  render json: { message: "success" }, :status => 200
  	  @upload["public_id"] = Cloudinary::Uploader.upload(@upload.image.path)["public_id"]
	    @user.uploads.push(@upload)
  	else
  	  render json: { error: @upload.errors.full_messages.join(',')}, :status => 400
  	end  		
  end

  private
    def upload_params
  	    params.require(:upload).permit(:image)
    end
end

photosite/app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def show
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.fetch(:user, {})
    end

end

photosite/app/helpers/application_helper.rb
module ApplicationHelper
end

photosite/app/helpers/cloud_helper.rb
module CloudHelper
end

photosite/app/helpers/images_helper.rb
module ImagesHelper
end

photosite/app/helpers/page_helper.rb
module PageHelper
end

photosite/app/helpers/slide_show_helper.rb
module SlideShowHelper
end

photosite/app/helpers/uploads_helper.rb
module UploadsHelper
end

photosite/app/views/cloud/show.html.erb
<% @user.uploads.all.each do |upload| %>
	<%= cl_image_tag(upload["public_id"],
		:height => 150,
		:width => 150,
		:crop => :fill)
	%>
	<% end %>

photosite/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photosite</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body> 

    <%= render "shared/navbar" %>

    <%= yield %>
  </body>
</html>

photosite/app/views/page/home.html.erb
<% if !current_user %>
	<div class="header">
		<h1>Welcome to our site</h1>
	</div>
	<div class="actions">   
   		<%= link_to 'Sign in', new_user_session_path,:class => "btn btn-lg btn-primary"%><br><br/>   	
   		<%= link_to 'Sign up', new_user_registration_path,:class => "btn btn-lg btn-success"%>
  </div>	
<% end %>

photosite/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container">
   
          	<% if current_user %>
          		<ul class="nav navbar-nav">					
				  <li class="active"><%= link_to "Home", user_path(current_user), class: "navbar-brand"%></li>
				  <li class="active"><%= link_to 'Upload photos', uploads_new_path(current_user)%></li>
				  <li class="active"><%= link_to 'Photos', cloud_show_path(current_user)%></li>   
				  <li class="active"><%= link_to 'Create SlideShow', slideshow_create_path(current_user)%></li>
				  <li class="active"><%= link_to 'My SlideShowes', slideshow_show_path(current_user)%></li>   
				</ul>
				<ul class="nav navbar-nav navbar-right">
			  		<li class="active"><%= link_to "Sign out", destroy_user_session_path,method: :delete %></li>
				</ul>
			<% else %>
			  <li class="active"><%= link_to "Home", root_path%></li>
   			<% end %>
		
	</div><!-- /.container-fluid -->
</nav>

photosite/app/views/slide_show/create.html.erb
<% @user.uploads.all.each do |upload| %>
	<%= link_to cl_image_tag(upload["public_id"],:height => 250,:width => 250),
		request.original_url + "/uploads" + upload["id"].to_s + "/edit"%>
<% end %>	

photosite/app/views/slide_show/show.html.erb
<% image = @user.uploads %>
<div class="bxslider">
  	<% image.all.each do |image| %>
		<%=cl_image_tag(image["public_id"],
		:height => 500,
		:width => 800)
	%>
	<% end %>
</div>

photosite/app/views/uploads/edit.html.erb
<script type="text/javascript" src="http://feather.aviary.com/js/feather.js"></script>

<!-- Instantiate Feather -->
<script type='text/javascript'>
	var featherEditor = new Aviary.Feather({
		apiKey: '0728ddae97b84c04bcd6adf4ef7fd5dc',
		apiVersion: 3,
		theme: 'light', // Check out our new 'light' and 'dark' themes!
		tools: 'all',
		appendTo: '',
		onSave: function(imageID, newURL) {
			var img = document.getElementById(imageID);
			img.src = newURL;
		},
		onError: function(errorObj) {
			alert(errorObj.message);
		}
	});
	function launchEditor(id, src) {
		featherEditor.launch({
			image: id,
			url: src
		});
		return false;
	}

	var imagepath = "<%= "http://res.cloudinary.com/dza2bty1l/image/upload/" + @upload["public_id"].to_s + "." + @upload["image_content_type"][6..-1].to_s %>";

</script>

<div id='injection_site'></div>

<img id='image1' src="<%= "http://res.cloudinary.com/dza2bty1l/image/upload/"+@upload["public_id"].to_s+"." + @upload["image_content_type"][6..-1].to_s %>"/>

<!-- Add an edit button, passing the HTML id of the image and the public URL of the image -->
<p><input type='image' value='Edit photo' onclick="return launchEditor('image1',imagepath);" /></p>

photosite/app/views/uploads/new.html.erb
<%= form_for([@user, @user.uploads.build], html: { multipart: true, class: "dropzone"}) do |f|  %>
	<div class="fallback">
	<%= f.file_field :image %><br>
	<%= f.submit "Upload" %>
  </div>
<% end %>

photosite/app/views/user/show.html.erb
<div class="actions">
	
</div>