Authorization/config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'omniauth_callbacks/facebook'
  end

  namespace :users do
    get 'omniauth_callbacks/vkontakte'
  end
  namespace :users do
    get 'omniauth_callbacks/twitter'
  end
    namespace :users do
    get 'omniauth_callbacks/github'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index, :destroy]
  root :to => 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Authorization/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :vkontakte, :twitter, :github]

   
  def self.find_for_facebook_oauth access_token
    if user = User.where(:username => access_token.extra.raw_info.name).first
      user
    else
      User.create!(:provider => access_token.provider,
        :url => "https://www.facebook.com/"+access_token.extra.raw_info.id,
        :username => access_token.extra.raw_info.name,
        :email => access_token.extra.raw_info.email,
        :password => Devise.friendly_token[0,20]) 
    end
  end

  def self.find_for_vkontakte_oauth access_token
    if user = User.where(:url => access_token.info.urls.Vkontakte).first
      user
    else 
      User.create!(:provider => access_token.provider, 
      	:url => access_token.info.urls.Vkontakte,
      	:username => access_token.info.name, 
      	:email => access_token.info.urls.Vkontakte+"@vk.com",
      	:password => Devise.friendly_token[0,20]) 
    end
  end

  def self.find_for_twitter_oauth access_token
    if user = User.where(:url => access_token.info.urls.Twitter).first
      user
    else 
      User.create!(:provider => access_token.provider, 
        :url => access_token.info.urls.Twitter,
        :username => access_token.info.name, 
        :email => access_token.info.urls.Twitter+"@tw.com",
        :password => Devise.friendly_token[0,20]) 
    end
  end

  def self.find_for_github_oauth access_token
    if user = User.where(:url => access_token.info.urls.GitHub).first
      user
    else 
      User.create!(:provider => access_token.provider, 
        :url => access_token.info.urls.GitHub,
        :username => access_token.info.name, 
        :email => access_token.info.urls.GitHub+"@gh.com",
        :password => Devise.friendly_token[0,20]) 
    end
  end

end

Authorization/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Authorization/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
  	@user = User.find_for_facebook_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end 

   def vkontakte
  	@user = User.find_for_vkontakte_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end

   def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Twitter"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end

   def github
    @user = User.find_for_github_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "GitHub"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

Authorization/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :nickname, :provider, :url, :password)
    end
end

Authorization/app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

Authorization/app/helpers/users_helper.rb
module UsersHelper
end

Authorization/app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Authorization"
    = csrf_meta_tags
    = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    %body{:style => "background-image: url(http://www.walldevil.com/wallpapers/a55/web-wallpaper-background-about-wallpaperweb-color-sky.jpg)"}  
    .container{:align => "center"}
      .content
        .row        
          .well.sidebar-nav
            - if !user_signed_in?         
              %h1{:style => "font-size: 60px; color: #FFE4C4;vertical-align:middle;"} Sign in 
              = link_to image_tag('https://www.facebook.com/images/fb_icon_325x325.png', size:"60x60"), user_facebook_omniauth_authorize_path
              = link_to image_tag('https://new.vk.com/images/safari_152.png', size:"60x60"), user_vkontakte_omniauth_authorize_path
              = link_to image_tag('http://trendingcurrentevents.com/wp-content/uploads/2015/01/twitter-icon.png', size:"60x60"), user_twitter_omniauth_authorize_path
              = link_to image_tag('https://assets-cdn.github.com/images/modules/logos_page/Octocat.png', size:"60x60"), user_github_omniauth_authorize_path
          - if user_signed_in?
            .span9
              = yield
            .span3
            %br
            = link_to image_tag('http://www.edu21.cap.ru/home/11099/2/knopka_pereiti_31.png',size:"150x60"), current_user.url, :style => "font-size: 20px;color: #FFE4C4;"
            %br
            %br
            = link_to image_tag('https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Mauritius_Road_Signs_-_Information_Sign_-_Out.svg/2000px-Mauritius_Road_Signs_-_Information_Sign_-_Out.svg.png',size:"150x60"), destroy_user_session_path, :method => :delete , :style => "font-size: 20px;color: #FFE4C4;"

Authorization/app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :nickname
    = f.text_field :nickname
  .field
    = f.label :provider
    = f.text_field :provider
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

Authorization/app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

Authorization/app/views/users/index.html.haml
- model_class = User.new.class
%table{:border => "3", :bordercolor => "000000", :style => "border-collapse:collapse; width: 100%;"}
  %thead{:style => "height:50px; text-align: center"}
    %tr{:bgcolor => "FFE4C4"}
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:provider)
      %th= model_class.human_attribute_name(:sign_in_count)
      %th= model_class.human_attribute_name(:updated_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody{:style => " text-align: center;"}
    - @users.each do |user|
      %tr
      %td{:bgcolor => "00FA9A"}= link_to user.username, user.url 
      %td{:bgcolor => "FFD700"}= user.provider
      %td{:bgcolor => "FFA500"}= user.sign_in_count
      %td{:bgcolor => "EE82EE"}= user.updated_at
      %td{:bgcolor => "00FFFF"}= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete

Authorization/app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

Authorization/app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
/%p
/ %b Nickname:
/  = @user.nickname
%p
  %b Provider:
  = @user.provider
%p
  %b Url:
  = @user.url

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path